import React, { Component, } from 'react';
import { View, Text, StyleSheet,Image,TextInput ,TouchableOpacity,StatusBar,Dimensions,ToastAndroid } from 'react-native';
import { Router, Scene,Actions} from 'react-native-router-flux';


export default class WayPointDescription extends Component {


  render() {
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.btnText}> Hi there! </Text>
          
        </View>
        <Text style={styles.title}> Some data here </Text>
        <View style={styles.img_cont}>
          <Image source={require('../assets/marker.png')} style={styles.splash_image}/>
        </View>
        <Text style={styles.description}>Hi there, this is short description generated by microsoft!</Text>

      </View>
    )
  }
}


const styles = StyleSheet.create({
  header: {
    justifyContent: 'center',
    flex: 2,
    flexDirection: 'row',
    backgroundColor: "#2988b9",
  },

  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",

  },
  title: {
    flex: 4,
    fontFamily: 'sans-serif-thin',
    fontSize: 40,
    textAlign: 'center',
  },
  img_cont: {
    flex:4,
    alignItems: 'center',
  },
  splash_image: {
    marginTop: 5,
    alignItems: 'center',

    width: 130,
    height: 130,
  },
  description: {
    flex: 5,
    fontFamily: 'sans-serif-thin',
    fontSize: 25,
    textAlign: 'center',
    marginTop: 35,
  },

  btnText: {
    textAlign: 'center',
    color: "#FFFFFF",
    fontFamily: 'sans-serif-thin',
    fontSize: 30,
  }
})
